// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Buy is an autogenerated mock type for the Buy type
type Buy struct {
	mock.Mock
}

// BuyItem provides a mock function with given fields: ctx, username, item
func (_m *Buy) BuyItem(ctx context.Context, username string, item string) error {
	ret := _m.Called(ctx, username, item)

	if len(ret) == 0 {
		panic("no return value specified for BuyItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, username, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBuy creates a new instance of Buy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuy(t interface {
	mock.TestingT
	Cleanup(func())
}) *Buy {
	mock := &Buy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
