// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	worker "avito-shop/internal/controller/worker"

	mock "github.com/stretchr/testify/mock"
)

// PoolI is an autogenerated mock type for the PoolI type
type PoolI struct {
	mock.Mock
}

// Shutdown provides a mock function with no fields
func (_m *PoolI) Shutdown() {
	_m.Called()
}

// Submit provides a mock function with given fields: task
func (_m *PoolI) Submit(task worker.Task) {
	_m.Called(task)
}

// NewPoolI creates a new instance of PoolI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPoolI(t interface {
	mock.TestingT
	Cleanup(func())
}) *PoolI {
	mock := &PoolI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
