// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Send is an autogenerated mock type for the Send type
type Send struct {
	mock.Mock
}

// SendCoin provides a mock function with given fields: ctx, fromUser, toUser, amount
func (_m *Send) SendCoin(ctx context.Context, fromUser string, toUser string, amount int) error {
	ret := _m.Called(ctx, fromUser, toUser, amount)

	if len(ret) == 0 {
		panic("no return value specified for SendCoin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = rf(ctx, fromUser, toUser, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSend creates a new instance of Send. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSend(t interface {
	mock.TestingT
	Cleanup(func())
}) *Send {
	mock := &Send{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
